# https://taskfile.dev
version: "3"
tasks:
  open: open https://soliditylang.org/

  opts:
    cmds:
      - |
        solc --help
        solc --version

  # Docker
  # docker run -v /local/path:/sources ethereum/solc:stable -o /sources/output --abi --bin /sources/Contract.sol
  # docker run ethereum/solc:stable --standard-json < input.json > output.json

  install-solc:
    desc: install solidity compiler
    # To install the most recent 0.4.x / 0.5.x version of Solidity you can also use brew install solidity@4 and brew install solidity@5, respectively.
    # https://github.com/ethereum/homebrew-ethereum/commits/master/solidity.rb
    cmds:
      - |
        brew update
        brew upgrade
        brew tap ethereum/ethereum
        brew install solidity

  # build from source
  # xcode
  # sudo xcodebuild -license accept
